[viewer]
    Title = "4927525Go语言博客"
    Description = "4927525Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/471282528"
    Zhihu = "https://www.zhihu.com/people/xi--8huan-gu-dai-hua-feng"
    Avatar = "https://pic1.zhimg.com/dda25331f645f813a4c93b2a7f20969e_xl.jpg?source=32738c0c"
    UserName = "4927525"
    UserDesc = "长得非常帅的程序员"
[system]
    Ip = "127.0.0.1"
    Port = "8003"
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "sf10R0BWDhC4u_VmVmpWZL9F7HSf04rWj89SDnJC"
    QiniuSecretKey = "XfkuWvm6LNMDSeMciKXpHgLu83TJEiDXVzLqnnPz"
    Valine = true
    ValineAppid = "nUKQ0ptSeRitpvvV2r5bUbBH-gzGzoHsz"
    ValineAppkey = "5XZAVEzbsVZK1EHrbZjsqp2y"
    ValineServerURL = "https://nukq0pts.lc-cn-n1-shared.com"